[versions]
kotlin = "2.2.21"
karate = "1.5.2"
amqp-client = "5.27.1"
qpidbrokerj = "10.0.0"
awaitility = "4.3.0"
assertj = "3.27.6"
grgit = "5.3.3"
kafka-clients = "4.1.1"
embedded-kafka-schema-registry = "8.1.0"
confluent = "8.1.0"

[libraries]
karate-core = { module = "io.karatelabs:karate-core", version.ref = "karate" }
karate-junit5 = { module = "io.karatelabs:karate-junit5", version.ref = "karate" }
amqp-client = { module = "com.rabbitmq:amqp-client", version.ref = "amqp-client" }
qpid-broker-core = { module = "org.apache.qpid:qpid-broker-core", version.ref = "qpidbrokerj" }
qpid-broker-plugins-amqp = { module = "org.apache.qpid:qpid-broker-plugins-amqp-0-8-protocol", version.ref = "qpidbrokerj" }
qpid-broker-plugins-memory-store = { module = "org.apache.qpid:qpid-broker-plugins-memory-store", version.ref = "qpidbrokerj" }
awaitility-kotlin = { module = "org.awaitility:awaitility-kotlin", version.ref = "awaitility" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-clients" }
kafka-avro-serializer = { module = "io.confluent:kafka-avro-serializer", version.ref = "confluent" }
kafka-json-schema-serializer = { module = "io.confluent:kafka-json-schema-serializer", version.ref = "confluent" }
kafka-protobuf-serializer = { module = "io.confluent:kafka-protobuf-serializer", version.ref = "confluent" }
embedded-kafka-schema-registry = { module = "io.github.embeddedkafka:embedded-kafka-schema-registry_3", version.ref = "embedded-kafka-schema-registry" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grgit-service = { id = "org.ajoberstar.grgit.service", version.ref = "grgit" }
